harness:
  name: accounts
  subdomain: accounts
  secured: false
  deployment:
    auto: false
    replicas: 1
    name: accounts
    port: 8080
    resources:
      requests:
        memory: "32Mi"
        cpu: "25m"
      limits:
        memory: "500Mi"
        cpu: "500m"
  service:
    auto: true
    name: accounts
    port: 8080
