harness:
  secrets:
    email-user:
    email-password:

  events:
    cdc:
    - app: workspaces
      types:
      - name: workspace
        events:
        - create
      - name: osbrepository
        events:
        - create

notification:
  channels:
    admins:
      from: info@opensourcebrain.org
      to:
        - info@opensourcebrain.org
    log:
      from: info@opensourcebrain.org
      to:
        - info@opensourcebrain.org
