harness:
  name: workspaces
  subdomain: workspaces
  service:
     port: 8080
     auto: true
     name: workspaces
  secured: false
  sentry: true
  livenessProbe:
    path: /api/live
    initialDelaySeconds: 45
    periodSeconds: 30
  readinessProbe:
    path: /api/ready
    initialDelaySeconds: 30
    periodSeconds: 30
  deployment:
    auto: true
    port: 8080
    volume:
      name: workspaces-images
      size: 4G
      mountpath: /usr/src/app/workspaces/static/workspaces
  secrets:
    - name: workspaces
      key: github-user
    - name: workspaces
      key: github-token
  dependencies:
    build:
      - cloudharness-base
      - cloudharness-flask
    soft:
      - events
      - common
    hard:
      - argo
  database:
    auto: false
    name: workspaces-postgres-host
    type: postgres
    port: 5432
    image: postgres:latest
    initialdb: workspaces
    user: workspace
    password: secret
    datavolume: /opt/data/
    pgdata: /opt/data/pgdata

github:
  user: ""
  token: ""
