apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspaces-db
  labels:
    app: {{ .Values.apps.workspaces.harness.database.name }}
{{ include "deploy_utils.labels" $ | indent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.workspaces.harness.database.name }}
  labels:
    app: {{ .Values.apps.workspaces.harness.database.name }}
{{ include "deploy_utils.labels" $ | indent 4 }}
spec:
  type: ClusterIP
  ports:
   - port: 5432
  selector:
   app: {{ .Values.apps.workspaces.harness.database.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apps.workspaces.harness.database.name }}
  labels:
    app: {{ .Values.apps.workspaces.harness.database.name }}
{{ include "deploy_utils.labels" $ | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.apps.workspaces.harness.database.name | quote }}
{{ include "deploy_utils.labels" $ | indent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Values.apps.workspaces.harness.database.name }}
        service: db
{{ include "deploy_utils.labels" $ | indent 8 }}
    spec:
      affinity:
          podAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: service
                      operator: In
                      values:
                        - db
                topologyKey: kubernetes.io/hostname
      containers:
      - name: {{ .Values.apps.workspaces.harness.database.name | default "workspaces-postgress" | quote }}
        image: {{ .Values.apps.workspaces.harness.database.image | quote }}
        imagePullPolicy: "IfNotPresent"
        env:
        - name: POSTGRES_DB
          value: {{ .Values.apps.workspaces.harness.database.initialdb | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.apps.workspaces.harness.database.user | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.apps.workspaces.harness.database.password | quote }}
        - name: PGDATA
          value: {{ .Values.apps.workspaces.harness.database.pgdata }}
        ports:
          - containerPort: {{ .Values.apps.workspaces.harness.database.port }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
        - name: workspaces-db
          mountPath: {{ .Values.apps.workspaces.harness.database.datavolume }}
      volumes:
      - name: workspaces-db
        persistentVolumeClaim:
          claimName: workspaces-db
---