apiVersion: v1
kind: Secret
metadata:
  name: workspaces
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  github-user: {{ default "" .Values.apps.workspaces.github.user }}
  github-token: {{ default "" .Values.apps.workspaces.github.token }}
