harness:
  subdomain: www
  secured: false
  deployment:
    auto: true
    port: 80
  service:
    auto: true
    port: 80
    name: portal
  sentry: true
  dependencies:
    soft:
      - accounts
      - common
      - volumemanager
      - workspaces
      - workflows
      - netpyne
      - nwb-explorer
      - jupyterhub
      - sentry
