name: Docker Image Build NWB Explorer

on:
  push:
    branches: [ master, dev*, feature/docker* ]
  pull_request:
    branches: [ master, dev*, feature/docker* ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Build the Docker image
      run: |
        cd applications/nwb-explorer
        docker build -t mynwbosb -f Dockerfile --no-cache .
    - name: Info on Docker image sizes
      run: |
        docker images
